package com.itechart;

import org.junit.Test;

public class UserDtoTest {
    /**
     * getters/setters and toString() method
     */
    @Test
    public void test1() {
        UserDtoV1 v1 = new UserDtoV1();
        v1.setId(1L);
        v1.setName("Alex");
        v1.setLastName("K");
        v1.setAge(20);
        System.out.println(v1.toString());

        UserDtoV2 v2 = new UserDtoV2();
        v2.setId(2L);
        v2.setName("John");
        v2.setLastName("Smith");
        v2.setAge(30);
        System.out.println(v2.toString());
    }

    /**
     * constructors
     */
    @Test
    public void test2() {
        UserDtoV1 v1 = new UserDtoV1(1L, "Alex", "K", 20);
        System.out.println(v1.toString());

        // constructor with all arguments was generated by Lombok
        UserDtoV2 v2 = new UserDtoV2(2L, "John", "Smith", 30);
        System.out.println(v2.toString());
    }

    /**
     * equals and hashcode
     */
    @Test
    public void test3() {
        UserDtoV1 user1 = new UserDtoV1(1L, "Alex", "K", 20);
        UserDtoV1 user2 = new UserDtoV1(1L, "Alex", "K", 20);
        System.out.println("UserDtoV1: "+user1.hashCode() + " and " + user2.hashCode());

        UserDtoV2 user3 = new UserDtoV2(2L, "John", "Smith", 30);
        UserDtoV2 user4 = new UserDtoV2(2L, "John", "Smith", 30);
        System.out.println("UserDtoV2: "+user3.hashCode() + " and " + user4.hashCode());
    }

}